### ISSUE TITLE
CDROM has not been defined or cannot be found

### ISSUE THREAD

**Issue by DagBjorndal** [raspberrypi/Raspberry-Pi-OS-64bit#101]
After installing 'abcde', I get the folowing message when trying to activate:

[ERROR] abcde: CDROM has not been defined or cannot be found

I hope this is helpful info.

**Comment by pelwell** [comment]
This is almost certainly the wrong place to report this issue - you'd be better off in the Raspberry Pi Forums, where they will almost certainly want to know if you have a CD-ROM drive attached...

**Comment by DagBjorndal** [comment]
Helpful interpretation for almost certainly non-professional readers:
Repository installed 'abcde' works in the 32 bit version of Raspberry Pi OS, with the USB connected CDROM in question, but not in the 64 bit version.

**Comment by pelwell** [comment]
> Repository installed 'abcde' works in the 32 bit version of Raspberry Pi OS, with the USB connected CDROM in question, but not in the 64 bit version

So there is no misunderstanding, is that a statement of fact according to your experience?

**Comment by lurch** [comment]
Do you get the same `lsusb` output in both the 32-bit and 64-bit versions of Raspberry Pi OS? What version numbers of `abcde` get installed into each OS?

**Comment by DagBjorndal** [comment]
Lsusb as expected. Same version abcde v2.9.3.

Turns out I have a dicey CDROM cable :-P

I can confirm that both _abcde_ and _dvdbackup_ works in Raspberry Pi OS 64 bit on my equipment. Case closed. Thanks.
