### ISSUE TITLE
Raspistill/raspivid disappear after I update the OS

### ISSUE THREAD

**Issue by chaitunya** [raspberrypi/Raspberry-Pi-OS-64bit#102]
When I downloaded and flashed the OS, raspistill and raspivid were there, but once I updated it, it got removed. Is this meant to happen? If not, how do I fix it?

**Comment by pelwell** [comment]
They were disabled because they weren't working properly. At some point they may be fixed and re-enabled.

**Comment by lurch** [comment]
See also #10 and #30

**Comment by chaitunya** [comment]
Thanks for the information. I'll close the issue now, I guess.
