### ISSUE TITLE
Support for HifiBerry Audio DAC+ PRO

### ISSUE THREAD

**Issue by friedrichs-repo** [raspberrypi/Raspberry-Pi-OS-64bit#103]
Hi everyone,
is there already a way to use hifiberry DACs with the 64bit raspberry pi os or plans to for supporting those in a future release? Out of the box it doesn't work for me yet:
'aplay -l' doesn't recognize it as a playback device and "dmesg | grep 'hifi' " returns
snd-rpi-hifiberry-dacplus soc: sound: ASoC: failed to init link HiFiBerry DAC+: -517

It worked out of the box in the 32bit version of raspberry pi os.

Thanks in advance,
Friedrich

**Comment by pelwell** [comment]
Do you have `dtoverlay=hifiberry-dacplus` in config.txt?

**Comment by friedrichs-repo** [comment]
Wonderful, that solved the problem - thanks a lot!
