### ISSUE TITLE
Remote SSH via Vscode does not work

### ISSUE THREAD

**Issue by WortWal** [raspberrypi/Raspberry-Pi-OS-64bit#104]

**Comment by pelwell** [comment]
It doesn't make a good impression if you can't be bothered to write any kind of description.

**Comment by WortWal** [comment]
> It doesn't make a good impression if you can't be bothered to write any kind of description.

Sorry I don't know how GitHub works I only have used it for this thread

**Comment by Lokathor** [comment]
@WortWal Hello. Could you give more information about what you tried to do, and what error messages you got, if any. This helps people try to reproduce the error, and then they can solve the problem a lot better.

**Comment by WortWal** [comment]
Sorry to all it was a problem of my firewall settings
