### ISSUE TITLE
os-release is different from Raspberry-32bit

### ISSUE THREAD

**Issue by daixiang0** [raspberrypi/Raspberry-Pi-OS-64bit#105]
Ref [issue](https://github.com/kubeedge/kubeedge/issues/2233#issuecomment-707515458).

For command `. /etc/os-release && echo $ID`

32 bit output:
```
raspbian
```

64 bit output:
```
debian
```

Is it a mistake or a change?

**Comment by XECDesign** [comment]
Raspberry Pi OS 32bit is built on top of Raspbian. 64bit is built on top of Debian. The os-release file comes from the source distro.

**Comment by lurch** [comment]
I don't want to "re-open old wounds", but this was previously discussed at length in #6
