### ISSUE TITLE
Dependency hell installing libsdl2-dev, but fixable by removing libraspberrypi-dev/doc

### ISSUE THREAD

**Issue by kaiomatico** [raspberrypi/Raspberry-Pi-OS-64bit#13]
Hi, I wanted to compile PPSSPP in 64 bit which requires libsdl2-dev which fails to install because several lib(e)gl(1)-mesa-dev libraries are not allowed to install because of libraspberrypi-dev.  
After then removing libraspberrypi-dev using:  
```
sudo dpkg -P libraspberrypi-doc
sudo dpkg -P libraspberrypi-dev
```
the libsdl2-dev and  lib(e)gl(1)-mesa-dev libraries install properly via apt. PPSSPP then compiles and runs fine in OpenGL mode. So I hope this bug report helps so in the near future we can install libsdl2-dev properly via apt :+1:  Anyway thank you for the awesome 64 bit OS release!!! :)

**Comment by XECDesign** [comment]
Sounds like the same root cause as https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/5

**Comment by pik33** [comment]
The same error while I tried to sudo apt-get install lazarus.

**Comment by XECDesign** [comment]
Fixed packages should be in the repo now

**Comment by kaiomatico** [comment]
Great the problem is solved by installing the latest apt updates (did a fresh install to make it super sure) :) I will close this issue now, thank you very much for the fast help
