### ISSUE TITLE
No audio with Compute Module 4

### ISSUE THREAD

**Issue by leggazoid** [raspberrypi/Raspberry-Pi-OS-64bit#134]
dmesg

bcm2835_audio: probe of bcm2835_audio failed with error -22

**Comment by pelwell** [comment]
There was a problem with the default CM4 .dtb file. It's fixed in the current rpi-update release, or you can just download that one file from here: https://github.com/Hexxeh/rpi-firmware/blob/master/bcm2711-rpi-cm4.dtb

**Comment by leggazoid** [comment]
Thanks pelwell, It is working.

**Comment by pelwell** [comment]
That change will be in future images, but it hasn't got there yet.
