### ISSUE TITLE
Latest 32 bit Raspberry OS - cannot change wallpaper

### ISSUE THREAD

**Issue by beng7** [raspberrypi/Raspberry-Pi-OS-64bit#139]
Hi
As indicated in the title, I just cannot change the wallpaper in Preferences > Appearances settings > Desktop; any modification is just not registered.
And when I run `sudo pcmanfm` -w /usr/share/rpd-wallpaper/new_wallpaper.jpg`, it still does not do anything but report that the "Desktop manager is not active"...
Yet upon reboot I can see the wallpaper of the login screen is changed to the new_wallpaper.jpg but once logged in the session wallpaper remains the sad temple.jpg

I was able to cahnge the session wallpaper by renaming new_wallpaper.jpg to temple.jpg but on reboot I noticed the login screen wallpaper is now a light grey colour...
This is true of the last 32 bit version of the OS, updated to the latest version, on a Pi 4B+.
Thanks for your help in adavance on the matter.

**Comment by lurch** [comment]
This is the issue-tracker for Raspberry-Pi-OS-64bit. For troubleshooting issues with 32 bit Raspberry OS you should ask for help on the [forums](https://www.raspberrypi.org/forums/).

**Comment by XECDesign** [comment]
Although nothing to do with 64-bit, you're seeing the issue because you're running the command as root.
