### ISSUE TITLE
MMAL API

### ISSUE THREAD

**Issue by davidecerutti** [raspberrypi/Raspberry-Pi-OS-64bit#146]
I was unable to install and use the picamera C++ libraries and the camera module on the 64 bit version because the MMAL libraries containing the raspistill commands were missing
is it possible to have MMAL apps on the raspberryPi os at 64bit?

**Comment by 6by9** [comment]
https://github.com/raspberrypi/userland/pull/586 but it's been reverted due to issues.

I've opened https://github.com/raspberrypi/userland/issues/688 as a placeholder.
