### ISSUE TITLE
VNC Server won't work

### ISSUE THREAD

**Issue by LoneProgrammer99** [raspberrypi/Raspberry-Pi-OS-64bit#15]
When I tried to turn on VNC via raspi-config, it showed me the following:
```
/usr/bin/vncserver-x11: error while loading shared libraries: libbcm_host.so: cannot open shared object file: No such file or directory
/usr/bin/vncserver-x11: error while loading shared libraries: libbcm_host.so: cannot open shared object file: No such file or directory
```
Because of this error, I'm not able to access my headless Pi's GUI. I'm pretty sure this is a 64-bit architecture specific thing, as it also didn't work on the 64-bit version of Ubuntu Server. Even if I enter `vncserver` into the command line, it stil gives me the same error as above, just once. If someone in the Raspberry Pi OS development team reads this, please keep this in mind and if there is a workaround available, and/or if you can contact RealVNC to create a 64-bit compatible version, that would be very helpful.

**Comment by PeterOGB** [comment]
See #12
