### ISSUE TITLE
Fails to boot after changing amount of GPU memory

### ISSUE THREAD

**Issue by rusmain** [raspberrypi/Raspberry-Pi-OS-64bit#151]
Pi4 (8Gb) with 03/04/2021 64 bit beta OS. Installation was o'k, updating via wi-fi is done.
Once amount of GPU memory is set to 812 Mb In Raspberry settings the system asks to restart.
Then only symbol "_" is on the screen and system is halted. switching power doesn't help.

**Comment by timg236** [comment]
Not a bug - see - https://www.raspberrypi.org/documentation/configuration/config-txt/memory.md. 

There's no benefit in allocating more than 256MB on Pi 4.
