### ISSUE TITLE
librosa and audioread package support on raspberry pi 

### ISSUE THREAD

**Issue by vs1612** [raspberrypi/Raspberry-Pi-OS-64bit#173]
Trying to install Librosa and audioread  package on raspberry pi using conda environment and also tried using PIP , but not able to install.

**Comment by lurch** [comment]
Is this different behaviour to the 32-bit Raspberry Pi OS, or does that also fail?

> but not able to install.

Error logs might be useful?

**Comment by vs1612** [comment]
Thank you for your response,
I am able to install now, i was missing with llvmlite package which is
needed for librosa.

In raspberry pi with conda for aarch64(64-bit) librosa is not supporting
correct? with 32-bit it is supporting.

If i am setting the environment using conda in 64-bit whether librosa
support is there or not?

Regards,
Vikas

**Comment by lurch** [comment]
It sounds like those are questions for conda and/or librosa (both of which I have absolutely no experience with), rather than questions about the 64-bit OS itself? Maybe you should ask for help on the https://www.raspberrypi.org/forums/ or at https://docs.conda.io/en/latest/help-support.html ?

**Comment by vs1612** [comment]
Ohk,

Thank you

Regards
Vikas

**Comment by vs1612** [comment]
The issue was resolved, first llvmlite has to be installed after that install librosa, it work for me.
