### ISSUE TITLE
Sysbench not available on apt

### ISSUE THREAD

**Issue by Notupus** [raspberrypi/Raspberry-Pi-OS-64bit#19]
APT is unable to get the Sysbench package seems like some repository problem

**Comment by XECDesign** [comment]
Sysbench doesn't exist in Debian Buster - https://packages.debian.org/search?suite=buster&searchon=names&keywords=sysbench

**Comment by Notupus** [comment]
I mean try.

**Comment by Notupus** [comment]
It worked on 32 bit

**Comment by XECDesign** [comment]
Because Raspbian doesn't clear old packages out when there's a new release. It probably has the old Stretch package in Buster.

**Comment by Notupus** [comment]
Ok, it seems I need a replacement

**Comment by lurch** [comment]
It **is** in buster-backports though: https://packages.debian.org/buster-backports/sysbench

Maybe you'll be able to download the arm64 deb and install it manually? Note that I've not tried that myself though, so it may or may not work!

**Comment by raginigupta6** [comment]
How can I install sysbench on Rasbpian (64bit)

**Comment by lurch** [comment]
https://backports.debian.org/Instructions/ might help, but that's obviously entirely unsupported! (I've not tried it myself)
