### ISSUE TITLE
Original Touch Screen is not working with 64bit on Pi 3B

### ISSUE THREAD

**Issue by ralf-9000** [raspberrypi/Raspberry-Pi-OS-64bit#196]
Hi,
I am trying to update my Touchscreen-Pi's with the 64bit image, the original 7" touchscreen is not working, only light rainbow pattern is visible. A new setup with the 32bit image is working fine. Have I to do a additional setup?
Ralf

**Comment by lurch** [comment]
Does this help? https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/185#issuecomment-952219630

**Comment by 6by9** [comment]
I've lost track of what has been released for the 64bit OS.
If 64bit has been updated in the same way as Bullseye 32 bit, then I'd expect to see ```display_auto_detect=1``` in config.txt. If so then adding ```dtoverlay=vc4-kms-dsi-7inch``` is not necessary.

More likely https://github.com/raspberrypi/linux/issues/4686. Add ```dtparam=i2c_vc_baudrate=50000``` to config.txt.

**Comment by ralf-9000** [comment]
Many thanks, 6by9 !!!

`dtparam=i2c_vc_baudrate=50000` has helped, works now!

`display_auto_detect=1` was already set and adding `dtoverlay=vc4-kms-dsi-7inch` has not helped. Adding the baudrate switch only was the key.

Ralf
