### ISSUE TITLE
xrdp doesn't work with Bullseye 64bit on Rpi4

### ISSUE THREAD

**Issue by fabnavigator** [raspberrypi/Raspberry-Pi-OS-64bit#209]
Using the Raspberry Pi Imager I just installed Raspberry Pi OS (64 bit) with the Raspberry Pi desktop on a Pi3 and a Pi4. Using Remote Desktop from Windows 10, I was able to connect to the Pi3, but not the Pi4. Doing exactly the same thing with the 32 bit OS it works on the Pi4.

Is there a workaround for this?

Pi3 -
```
fabnav@sandbox-pi3:~ $ sudo systemctl status xrdp
● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-02-12 09:28:52 EST; 39min ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 560 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
    Process: 572 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 581 (xrdp)
      Tasks: 2 (limit: 780)
        CPU: 3.220s
     CGroup: /system.slice/xrdp.service
             ├─ 581 /usr/sbin/xrdp
             └─3529 /usr/sbin/xrdp

Feb 12 10:06:56 sandbox-pi3 xrdp[3529]: [INFO ] xrdp_wm_log_msg: sesman connect ok
Feb 12 10:06:56 sandbox-pi3 xrdp[3529]: [INFO ] sesman connect ok
Feb 12 10:06:56 sandbox-pi3 xrdp[3529]: [INFO ] sending login info to session manager, please wait...
Feb 12 10:06:57 sandbox-pi3 xrdp[3529]: [INFO ] xrdp_wm_log_msg: login successful for display 10
Feb 12 10:06:57 sandbox-pi3 xrdp[3529]: [INFO ] login successful for display 10
Feb 12 10:06:57 sandbox-pi3 xrdp[3529]: [INFO ] loaded module 'libxup.so' ok, interface size 10296, version 4
Feb 12 10:06:57 sandbox-pi3 xrdp[3529]: [INFO ] started connecting
Feb 12 10:06:57 sandbox-pi3 xrdp[3529]: [INFO ] lib_mod_connect: connecting via UNIX socket
Feb 12 10:06:57 sandbox-pi3 xrdp[3529]: [INFO ] lib_mod_log_peer: xrdp_pid=3529 connected to X11rdp_pid=1252 X11rdp_uid=1001 X11rdp_gid=1001 client_ip=::ffff:192.168.0>
Feb 12 10:06:57 sandbox-pi3 xrdp[3529]: [INFO ] connected ok
```

Pi4 -
```
fabnav@sandbox-pi4:~ $ sudo systemctl status xrdp
● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-02-12 10:02:37 EST; 5min ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 2353 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
    Process: 2361 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 2362 (xrdp)
      Tasks: 3 (limit: 1830)
        CPU: 601ms
     CGroup: /system.slice/xrdp.service
             ├─2362 /usr/sbin/xrdp
             ├─3138 /usr/sbin/xrdp
             └─3238 /usr/sbin/xrdp

Feb 12 10:08:18 sandbox-pi4 xrdp[3238]: [WARN ] local keymap file for 0x00000409 found and doesn't match built in keymap, using local keymap file
Feb 12 10:08:18 sandbox-pi4 xrdp[3238]: [INFO ] connecting to sesman ip 127.0.0.1 port 3350
Feb 12 10:08:18 sandbox-pi4 xrdp[3238]: [INFO ] xrdp_wm_log_msg: sesman connect ok
Feb 12 10:08:18 sandbox-pi4 xrdp[3238]: [INFO ] sesman connect ok
Feb 12 10:08:18 sandbox-pi4 xrdp[3238]: [INFO ] sending login info to session manager, please wait...
Feb 12 10:08:18 sandbox-pi4 xrdp[3238]: [INFO ] xrdp_wm_log_msg: login successful for display 10
Feb 12 10:08:18 sandbox-pi4 xrdp[3238]: [INFO ] login successful for display 10
Feb 12 10:08:18 sandbox-pi4 xrdp[3238]: [INFO ] loaded module 'libxup.so' ok, interface size 10296, version 4
Feb 12 10:08:18 sandbox-pi4 xrdp[3238]: [INFO ] started connecting
Feb 12 10:08:18 sandbox-pi4 xrdp[3238]: [INFO ] lib_mod_connect: connecting via UNIX socket
```

**Comment by lurch** [comment]
Do any of the other issues help? https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/search?q=xrdp&type=issues

**Comment by fabnavigator** [comment]
Thank you for checking, but they do not.

**Comment by XECDesign** [comment]
Don't know enough about xrdp to figure out why it's not working, but I can confirm that it's not. Switching to the 32-bit release didn't work for me either, but it seemed fine on a pi zero.

I believe this is @spl237's domain.

**Comment by spl237** [comment]
> I believe this is @spl237's domain.

Sadly not! We don't support xrdp - there have been discussions on the forums about changes and workarounds to make it work under mutter, but it's not something I have either the knowledge or the time to work on myself, I'm afraid.

With VNC (which we do support), the fix is to roll back to openbox rather than mutter. I suspect this is also the fix for xrdp.

**Comment by spl237** [comment]
FWIW, https://github.com/neutrinolabs/xrdp/discussions/2050 is a discussion about the details of xrdp running on bullseye, so people have got it working; it may be worth raising an issue with Neutrino Labs?

**Comment by spl237** [comment]
The server is already installed in Raspberry Pi OS - just enable VNC on the "interfaces" page of Raspberry Pi Configuration. The client can be freely downloaded from RealVNC's website at https://www.realvnc.com/en/connect/download/viewer/

**Comment by fabnavigator** [comment]
Am I correct in saying that this viewer costs $ each month, or am I missing something?

**Comment by spl237** [comment]
No - from the download page - "Do I need to license the software?

No. VNC® Viewer is always free to use. Just accept the EULA the first time you run."

**Comment by fabnavigator** [comment]
So, I'm making progress, but I haven't found out how to configure vnc server on my headless pi. I'm sure I need to edit some settings in some file sonewhere...

**Comment by hydra3333** [comment]
Well, I just enabled VNC on the "interfaces" page of Raspberry Pi Configuration without configuration.

Then on my Win10 PC, downloaded the Standalone x64 Client from https://www.realvnc.com/en/connect/download/viewer/ and ran it.
I reckon I needed to create an account (easy) with RealVNC, then created a new connection and it connected and worked just fine.

good luck.

**Comment by fabnavigator** [comment]
@hydra3333, @lurch: Thank you. It was that simple. I think I read too much stuff about this.

Any thoughts about if I should close this xrdp issue?

**Comment by pelwell** [comment]
As the opener, you get to decide - but I see no reason not to close it. xrdp may work with mutter in her future, but this issue won't make it happen any faster.

**Comment by MosephV** [comment]
I was having the same issue with xrdp to a Pi3 running the 64bit Raspberry OS. This comment/discussion, [https://github.com/neutrinolabs/xrdp/issues/2053#issuecomment-1038142308](url), linked to this one: [https://github.com/neutrinolabs/xrdp/issues/2060#issuecomment-979322159](url), which worked for me.

> 
> Also, try this; can you edit the file `/etc/X11/xrdp/xorg.conf`, and find this line:-
> 
> ```ini
>     Option "DRMDevice" "/dev/dri/renderD128"
> ```
> 
> Comment it out, and replace it with a line with no value:-
> 
> ```ini
>     #Option "DRMDevice" "/dev/dri/renderD128"
>     Option "DRMDevice" ""
> ```
> 
> That should stop the driver trying to use the DRI device, and may prevent the hang.

I rebooted my Pi afterwards

Hope it works for anyone else experiencing this
