### ISSUE TITLE
Wifi lost after dist-upgrade on rpi4B rev 1.5

### ISSUE THREAD

**Issue by rkarlsba** [raspberrypi/Raspberry-Pi-OS-64bit#217]
I just got this rpi4 2GB rev 1.5 and it works well, or did, until I did a dist-upgrade and it lost contact with wifi altogether. It seems it's a driver issue - I can't even iwlist wlan0 scan or up the nic. I tried to upgrade firmware, but it didn't help anything. I've tried to reinstall several times (since it's not in use yet) and have reproduced the error all of those times. It goes like this (the fourth, the fift):

- Put 2022-01-28-raspios-bullseye-arm64-lite.img on an sd card.
- Touch /boot/ssh and setup /boot/wpa_supplicant.conf, add enable_uart=1 to config.txt (the latter only for debugging, it reproduces well without it, but I don't have anything with hdmi here).
- Boot the OS, set new password.
- Check networking - it all works (only tested on 2.4GHz - 5GHz didn't seem to work). I got valid IPv4 and IPv6 addresses.
- run 'apt update && apt full-upgrade'
(the minor flaw)
- Reboot
(and the major lift)
- And check network settings. Nothing on the wifi. NIC is down.
(The baffled king composing Hallelujah)

The firmware was a tad old, so I upgraded to the latest firmware from Thu 10 Mar 2022 11:57:12 AM UTC and it didn't help anything.

PS: There's a line in dmesg that might be relevant, but I'm not sure: cfg80211: loaded regulatory.db is malformed or signature is missing/invalid

**Comment by yutayu** [comment]
[   28.364825] ieee80211 phy0: brcmf_cfg80211_start_ap: Set Channel failed: chspec=4108, -52
uname -r
5.15.30-v7l+

This also happens at 32bit.
No SSID releases.

**Comment by pelwell** [comment]
Starting with a clean download of the 64-bit RPi-OS and running `sudo apt update && sudo apt full-upgrade` didn't cause any problems on a rev 1.2 Pi 4B.

Can anyone experiencing this issue post:
1. the initial OS version - 32 vs 64, Lite vs Full, image date if known,
2. the upgrade method - `dist-upgdate`, `full-upgrade`,
3. the output of `tail /proc/cpuinfo`,
4. the whole of `dmesg` shortly after boot?

**Comment by ghollingworth** [comment]
Also what channel/country are you selecting?

**Comment by rkarlsba** [comment]
> Starting with a clean download of the 64-bit RPi-OS and running `sudo apt update && sudo apt full-upgrade` didn't cause any problems on a rev 1.2 Pi 4B.

It does on rev 1.5

> Can anyone experiencing this issue post:
> 
>     1. the initial OS version - 32 vs 64, Lite vs Normal vs Full, image date if known,

Last I checked, the kernel is the same for all of these, and I used 2022-01-28-raspios-bullseye-arm64-lite.img and as [yutayu](https://github.com/yutayu) says, it's the same on 32bit.

>     2. the upgrade method - `dist-upgdate`, `full-upgrade`,

If you look at the code, dist-upgrade is just an alias for full-upgrade. And I have tried them both - same result.

>     3. the output of `tail /proc/cpuinfo`,

I guess you're looking for these

Hardware        : BCM2835
Revision        : b03115
Serial          : 100000004dc89f36
Model           : Raspberry Pi 4 Model B Rev 1.5

>     4. the whole of `dmesg` shortly after boot?

https://paste.debian.net/1236251/

**Comment by rkarlsba** [comment]
> Also what channel/country are you selecting?

It was set to NO, since I'm in Norway, and that has worked well on other pis. I've tried SE and UK as well with the same result.

**Comment by pelwell** [comment]
There is nothing obviously wrong in your kernel log. How about `iwlist channel` and `iwconfig`?

**Comment by rkarlsba** [comment]
root@raspberrypi:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether e4:5f:01:9e:fd:83 brd ff:ff:ff:ff:ff:ff
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether e4:5f:01:9e:fd:84 brd ff:ff:ff:ff:ff:ff
root@raspberrypi:~#

**Comment by yutayu** [comment]
> * the initial OS version - 32 vs 64, Lite vs Normal vs Full, image date if known,
32bit,Normal,1-28
uname -a
Linux raspberrypi 5.15.30-v7l+ #1536 SMP Mon Mar 28 13:51:42 BST 2022 armv7l GNU/Linux
 
> * the upgrade method - `dist-upgdate`, `full-upgrade`,
full-upgrade 
> * the output of `tail /proc/cpuinfo`,
tail /proc/cpuinfo
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2711
Revision	: c03112
Serial		: 10000000c2ebe06a
Model		: Raspberry Pi 4 Model B Rev 1.2
 
> * the whole of `dmesg` shortly after boot,
[log.txt](https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/files/8387766/log.txt)

> * the WLAN channel and country code (as @ghollingworth asks)?
13
JP

**Comment by pelwell** [comment]
Installing and enabling hostapd is a non-standard configuration and should always be mentioned in bug reports. However, I think @rkarlsba is _not_ using hostapd - am I right?

**Comment by yutayu** [comment]
I changed wifi channel 13 to 11 and it works.

**Comment by pelwell** [comment]
@rkarlsba As part of the investigation, what is your current WLAN channel and (if you can) does changing it help?

**Comment by pelwell** [comment]
To see if this failure is as the result of the kernel change, you can revert to a 5.10 kernel with `sudo rpi-update 770ca2c2`.

**Comment by rkarlsba** [comment]
@pelwell It was at channel 12. I moved it to channel 10 and now it works. Thanks :)

I'm using openwrt, meaning hostapd, it seems

**Comment by rkarlsba** [comment]
And yes, I can confirm that rolling back to 5.10 "fixes" this.

**Comment by pelwell** [comment]
Thanks - that should be enough to work on for now.

**Comment by rkarlsba** [comment]
oh - btw - no errors in the kernel log about regulatory.db in 5.10

**Comment by rkarlsba** [comment]
5.15 gave me these 

Mar 29 18:43:01 pi kernel: [    5.119194] cfg80211: Loading compiled-in X.509 certificates for regulatory database
Mar 29 18:43:01 pi kernel: [    5.154400] cfg80211: loaded regulatory.db is malformed or signature is missing/invalid

**Comment by pelwell** [comment]
I can reproduce the issue here - the 5.15 kernel seems to be restricting WiFi to the lowest common denominator of channels 1-11.

**Comment by rkarlsba** [comment]
…which looks like a bad regulatory.db ;)

**Comment by pelwell** [comment]
Yes, probably, but in my experiences it's better not to jump to conclusions.

**Comment by rkarlsba** [comment]
I was guessing, not concluding ;)

**Comment by pelwell** [comment]
Would you care to guess what the solution is?

**Comment by rkarlsba** [comment]
Replace regulatory.db with a valid file, one that 5.15 can accept

**Comment by XECDesign** [comment]
FWIW, I'm seeing the ` loaded regulatory.db is malformed or signature is missing/invalid` message on 5.10 as well on my pi400, running pios arm64. Might be a red herring.

**Comment by rkarlsba** [comment]
Perhaps 5.15 is enforcing that? dunno

**Comment by pelwell** [comment]
Updating to the latest regulatory.db removes the error message but doesn't solve the problem:
1. Download https://mirrors.edge.kernel.org/pub/software/network/wireless-regdb/wireless-regdb-2022.02.18.tar.xz
2. Extract `regulatory.db` and `regulatory.db.p7s`.
3. Copy them to `/lib/firmware/`.
4. Reboot.

**Comment by rkarlsba** [comment]
Confirmed - doesn't help

**Comment by pelwell** [comment]
I've traced the problem to a downstream commit that got replaced by an upstream commit (yay), which was then reverted by another upstream commit (boo). The absence of the commit causes it to silently (unless you turn on super verbose brcmfmac tracing) configure the country codes in the WLAN chip, making it default to a worldwide-safe mode.

https://github.com/raspberrypi/linux/commit/6f921e98008589258f97243fb6658d09750f0a2f is the replacement patch.

**Comment by rkarlsba** [comment]
Thanks a bunch. Is this in the repos yet?

**Comment by rkarlsba** [comment]
what is 'a bit'?

**Comment by rkarlsba** [comment]
> It's an English phrase which, in this context, means a short interval of time.

I know what it means, but I also know that "a short interval of time" is quite relative ;)

**Comment by rkarlsba** [comment]
- Dad! How far away is Mars?
- Only five minutes or so, why?
- Cool, let's walk!

**Comment by rkarlsba** [comment]
Thanks - works well :)

**Comment by rkarlsba** [comment]
Is this fed to the apt repos yet?

**Comment by pelwell** [comment]
The apt package update should be live now.

**Comment by rkarlsba** [comment]
Thank you - and have a nice weekend :)
