### ISSUE TITLE
CONFIG_USB_FUNCTIONFS disabled in kernel

### ISSUE THREAD

**Issue by burtyb** [raspberrypi/Raspberry-Pi-OS-64bit#22]
Could CONFIG_USB_FUNCTIONFS be enabled in the kernel please (I've previously been using it to setup composite USB Gadgets).

**Comment by pelwell** [comment]
> (I've previously been using it to setup composite USB Gadgets)

Was this in custom kernel builds? I can't find any evidence that we've ever defined it.

**Comment by maxnet** [comment]
>Could CONFIG_USB_FUNCTIONFS be enabled in the kernel please (I've previously been using it to 
>setup composite USB Gadgets).

You can use the configfs interface provided through CONFIG_USB_CONFIGFS and friends (CONFIG_USB_CONFIGFS_*) instead, to setup composite USB gadgets.

**Comment by burtyb** [comment]
Yikes, I'm sorry you're right I'd mixed up two projects.
