### ISSUE TITLE
Default SSH username/password changed?

### ISSUE THREAD

**Issue by got3nks** [raspberrypi/Raspberry-Pi-OS-64bit#220]
Just flashed the 64bit image onto the SD card and created the empty "ssh" file in the root directory.

I can connect with SSH but the usual user/password default "pi/raspberry" doesn't work.

```
~ % ssh pi@192.168.1.200
pi@192.168.1.200's password:
Permission denied, please try again.
```

What is the default username and password for 64bit Raspberry Pi OS?

**Comment by JamesH65** [comment]
There is no longer a default username/password. Please see https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/
