### ISSUE TITLE
cant ssh into pi

### ISSUE THREAD

**Issue by nmcc1212** [raspberrypi/Raspberry-Pi-OS-64bit#223]
i created the ssh file on the boot partition using `touch ssh` on macos terminal

i am using `ssh pi@192.168.68.139`

the password i am using is `raspberry`

i don't see why this doesn't work

i literally copy/paste the word above into terminal and it didn't work

**Comment by nmcc1212** [comment]
this is the terminal output
```
pi@192.168.68.139's password:
Permission denied, please try again.
```

**Comment by nmcc1212** [comment]
fixed by creating a custom user and enabling ssh from within pi imager

**Comment by lurch** [comment]
> i don't see why this doesn't work

See https://www.raspberrypi.com/documentation/computers/configuration.html#setting-up-a-headless-raspberry-pi and https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/

**Comment by nmcc1212** [comment]
me neither

**Comment by nmcc1212** [comment]
ah, didn't notice this change, thanks!
