### ISSUE TITLE
libgtk-x11-2.0.so.0

### ISSUE THREAD

**Issue by botjuice** [raspberrypi/Raspberry-Pi-OS-64bit#23]
error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

i get this error on the 64-bit OS but not on the 32-bit OS

**Comment by XECDesign** [comment]
When running what?

**Comment by botjuice** [comment]
I was trying to run a raspberry pi version of balenaEtcher

**Comment by XECDesign** [comment]
They don't have a pi version on their site. You'll need to ask whoever you got the build from for support, it doesn't sound like an issue with the OS.
