### ISSUE TITLE
The usb flash drive cannot be read normally

### ISSUE THREAD

**Issue by JoveH-H** [raspberrypi/Raspberry-Pi-OS-64bit#24]
When the usb flash drive is inserted, the system prompts an error!

**Comment by kencormack** [comment]
The following information might be helpful...
What make/model of flash drive...
The exact error message...
Any relevant dmesg or syslog messages...
Whether the flash drive is partitioned/formatted...
The type of filesystem on the flash drive...

**Comment by JoveH-H** [comment]
My usb flash disk is exfat, so I can't. Sorry.
