### ISSUE TITLE
SSL error for Perl/Mojolicious Apps 

### ISSUE THREAD

**Issue by bislink** [raspberrypi/Raspberry-Pi-OS-64bit#240]
`wget https://spanel.gnani.xyz:44042` gives the following error. 

```
GnuTLS: Error in the pull function. 
Unable to establish SSL connection.
```

Apart from this, I cannot access the/any Mojolicious app that is running on a custom port with SSL whereas `https://spanel.gnani.xyz` (apache2) shows no error.

Perl Version 5.32.1 on Raspberry Pi 4 with 8 GB RAM. 

On Brave and Edge, I get error : ERR_CONNECTION_RESET

Reinstalling both `wget` and `openssl` did nothing.

appreciate help fixing this issue.

**Comment by pelwell** [comment]
I get the same result as @XECDesign - it's not a Raspberry Pi-specific issue, and since the browsers also fail it's looking a lot like a server problem.

**Comment by bislink** [comment]
`wget https://spanel.gnani.xyz:44042` is not served by apache2 but Perl/Mojolicious

**Comment by bislink** [comment]
Error after reinstalling `libmojoicious-perl` for `wget --spider https://spanel.gnani.xyz:44042` : 

```
GnuTLS: The TLS connection was non-properly terminated.                                                                                                     Unable to establish SSL connection.
```

**Comment by pelwell** [comment]
All clients seem to agree that https://spanel.gnani.xyz:44042 is not sending any data - what do you expect us to do?

**Comment by bislink** [comment]
Same app without SSL seems to work: http://spanel.gnani.xyz:44040

**Comment by pelwell** [comment]
Are you actually telling us that spanel.gnani.xyz is a site hosted on a Pi 4?

**Comment by bislink** [comment]
Yes. I am running multiple sites on a Pi 4 8 GB RAM with apache2 and some Perl/Mojo apps with custom ports!

**Comment by pelwell** [comment]
Read the server log, check your certificate, etc.

**Comment by bislink** [comment]
The same certificate works ok for apache2. `https://spanel.gnani.xyz`

**Comment by pelwell** [comment]
It doesn't look as though you are alone - I found this similar error (and the Mojolicious repo): https://github.com/mojolicious/mojo/issues/1876
