### ISSUE TITLE
Have PiHole running on raspberry pi  lite 64 bit OS...can I install PiVPN on this OS?

### ISSUE THREAD

**Issue by aaronac8** [raspberrypi/Raspberry-Pi-OS-64bit#245]
Is the 32 bit OS lite better for PiHole and PiVPN?  Or can I use the 64 bit lite OS for both of these servers on my single raspberry pi?  Thank you

**Comment by popcornmix** [comment]
Questions like this are best asked on the forum.

But PiHole or PiVPN (or both) will run just fine on either 32-bit or 64-bit.
