### ISSUE TITLE
Ubuntu server 64 bit can access only 4gb not 8gb ram on a new pi 8gb model

### ISSUE THREAD

**Issue by samlearner-prog** [raspberrypi/Raspberry-Pi-OS-64bit#25]
I have researched ubuntu forums as well, but most discussions point towards a firmware issue.  pls help check.

**Comment by kencormack** [comment]
This forum is for reporting problems with the "Raspberry Pi OS" 64-bit beta OS, not Ubuntu Server 64-bit

**Comment by satmandu** [comment]
@samlearner-prog I don't have my 8Gb pi yet but can you see if the official raspberry pi foundation kernels work properly with the 8gb rpi4b?

Try using this script to build a kernel package deb that you can install on ubuntu arm64 server:

https://gist.github.com/satmandu/a507c59d84737f6d29ff353395819d51

**Comment by kencormack** [comment]
The official "Raspbian" Buster (32-bit) image should work just fine.  I'm not a developer for this 64-bit effort.  I was just pointing out that your thread seems to suggest you wanted to talk about Ubuntu Server, and not "Raspberry Pi OS" (the name for the Pi's beta 64-bit kernel.)  Just wanted to make sure you were aware this forum isn't for discussing anything but the beta.

**Comment by samlearner-prog** [comment]
@kencormack - i realised just a little too late.  apologies. 
@ satmandu  - many thanks for the pointer. 
i will close
