### ISSUE TITLE
My pi doesn't turn on. Only if i connect it with external monitor it is turning or else it gets power but no out put in the monitor i have even edited the configuration.txt file just uncommented the hdmi_force_hotplug=1 but no use

### ISSUE THREAD

**Issue by Navinlakshman-01** [raspberrypi/Raspberry-Pi-OS-64bit#252]
My pi doesn't turn on. Only if i connect it with external monitor it is turning or else it gets power but no out put in the monitor i have even edited the configuration.txt file just uncommented the hdmi_force_hotplug=1 but no use pls help me with this

**Comment by popcornmix** [comment]
This repo is for issues with specific packages in RPiOS 64-bit.
For general troubleshooting what is causing your issue, a post in the forum would be best:
https://forums.raspberrypi.com/index.php
