### ISSUE TITLE
ssh access installing headless

### ISSUE THREAD

**Issue by nettuno77** [raspberrypi/Raspberry-Pi-OS-64bit#37]
using same procedure of ever, the username "pi" has a different password

**Comment by ghollingworth** [comment]
No it doesn't, it's still "raspberry"

Do you get:

pi@192.168.1.144's password:
Permission denied, please try again.

**Comment by nettuno77** [comment]
yes, I've tryed many times... but no luck. Also attempt different passwords... but still no luck

**Comment by nettuno77** [comment]
ok, I try to type slowly, very slowly, and get login.
Then I logout and try many times to login typing password at different speed, but every time I logged in successfully. Buh, I don't know, so we can close this issue. Strange behaviour.

**Comment by pelwell** [comment]
It just worked for me with a clean install. I'd close this if I could.

**Comment by nettuno77** [comment]
No, nothing, it continue to give me Permission denied....
But I'm trying with a pi 3B+, I don't know if it matters
