### ISSUE TITLE
unable to upgrade package linux-image-4.19.0-9

### ISSUE THREAD

**Issue by tomerrr** [raspberrypi/Raspberry-Pi-OS-64bit#54]
```
apt list --upgradable
Listing... Done
linux-image-4.19.0-9-rt-arm64/stable 4.19.118-2+deb10u1 arm64 [upgradable from: 4.19.118-2]
```
sudo apt upgrade
```
Unpacking linux-image-4.19.0-9-rt-arm64 (4.19.118-2+deb10u1) over (4.19.118-2) .
dpkg: error processing archive /var/cache/apt/archives/linux-image-4.19.0-9-rt-a
rm64_4.19.118-2+deb10u1_arm64.deb (--unpack):
 unable to make backup link of './boot/System.map-4.19.0-9-rt-arm64' before inst
alling new version: Operation not permitted
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
W: Last kernel image has been removed, so removing the default symlinks
Errors were encountered while processing:
 /var/cache/apt/archives/linux-image-4.19.0-9-rt-arm64_4.19.118-2+deb10u1_arm64.deb
```
i'm using kernel version
 Linux raspberrypi 5.4.44-v8+ #1320 SMP PREEMPT Wed Jun 3 16:20:05 BST 2020 aarch64 GNU/Linux
after my lib/modules directory got deleted somehow, and some files on /boot ,
so i used rpi-update to update to the latest beta kernel, which got my Pi booting again and loading all modules

**Comment by XECDesign** [comment]
linux-image-4.19.0-9 isn't ours. It's a Debian package trying to write to /boot, so that's never going to work. We use raspberrypi-kernel instead.

> @XECDesign what are the changes?
> rpi-update currently writes to /boot, /lib/modules, /opt/vc
> I think /opt/vc is no longer used. Is /lib/modules still the same?

Nothing relevant to this issue. As you say, /lib/modules is still the same, /opt/vc/ isn't used.

**Comment by tomerrr** [comment]
i think i understand what's the issue - I manually install linux-headers deb package from the other  [thread](https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/4) which installs linux-image package. and now apt is trying to upgrade that package to an older version

**Comment by tomerrr** [comment]
workaround solution: 
sudo umount /boot
sudo apt upgrade
(updates fine, warns about missing headers package)
sudo mount /dev/mmcblk0p1 /boot --type vfat

**Comment by shunobies** [comment]
tomerr,
For me I had to run 
sudo rpi-update
sudo umount /boot
sudo apt --fix-broken install
reboot
Everything came up perfectly.
