### ISSUE TITLE
The system was unable to go into root mode, indicating a fault identification

### ISSUE THREAD

**Issue by wujianzhang1237** [raspberrypi/Raspberry-Pi-OS-64bit#55]
PI @ raspberrypi: ~ $su
Password:
Su: Identify the fault
PI @ raspberrypi: ~ $su root
Password:
Su: Identify the fault
PI @ raspberrypi: ~ $su root

**Comment by XECDesign** [comment]
`sudo -i`

Or if you want to use `su`, set a root password first with `sudo passwd root`.

**Comment by wujianzhang1237** [comment]
> `sudo -i`
> 
> 或者，如果要使用`su`，请先使用设置根密码`sudo passwd root`。

good，thanks。
