### ISSUE TITLE
Weird sounds at HDMI audio output at LG monitor speakers

### ISSUE THREAD

**Issue by domi555** [raspberrypi/Raspberry-Pi-OS-64bit#58]
I have an LG Monitor and there are coming mysterious sounds out of the integrated speakers. (e.g. when I click on the sound icon of the top menu or when I write some commands into the terminal)
Does anyone have similiar problems?

**Comment by lurch** [comment]
Is this different behaviour between Raspberry Pi OS 64-bit and Raspberry Pi OS 32-bit ?
Do you have any other HDMI devices which are able to "correctly" play sounds through your LG monitor speakers?

**Comment by domi555** [comment]
I found the reason for my problems. It was orca reader.
Sorry for that, I couldn't hear it before because the volume was so low and it sounded really weird.
