### ISSUE TITLE
the touch input with the official touchscreen is inaccurate

### ISSUE THREAD

**Issue by Sieger1004** [raspberrypi/Raspberry-Pi-OS-64bit#59]
The  and y coordinates of the touch input are doubled. in the top left corner its more or less accurate, but touched in the middle it thinks I touched the bottom right corner.

**Comment by Sieger1004** [comment]
*Edit:
After a reinstall only the x coordinate is doubled using the touchscreen

**Comment by lurch** [comment]
Duplicate of #8 ?
