### ISSUE TITLE
GPIO LCD driver for 64 bit OS

### ISSUE THREAD

**Issue by openoms** [raspberrypi/Raspberry-Pi-OS-64bit#64]
Did anyone make the 3.5" GPIO display http://www.lcdwiki.com/3.5inch_RPi_Display work with the 64bit Raspberry OS yet?

Related issue: 
https://github.com/goodtft/LCD-show/issues/212

**Comment by tux1c** [comment]
https://github.com/tux1c/wavesharelcd-64bit-rpi

**Comment by kilrau** [comment]
> https://github.com/tux1c/wavesharelcd-64bit-rpi

Works like a charme if `/boot/config.txt` options are set correctly: https://github.com/tux1c/wavesharelcd-64bit-rpi/issues/3 !

**Comment by kilrau** [comment]
Why close? The LCD still needs manual driver installation and fiddling with config options. It should work out of the box, until then this issue should stay open imho.

**Comment by ghollingworth** [comment]
This display is a non-standard third party device, why do you think it should work 'out of the box'?  The instructions for installing it just need fixing on the originator's website

**Comment by kilrau** [comment]
Alright.
