### ISSUE TITLE
Not able to compile custom kernel

### ISSUE THREAD

**Issue by rbollampally** [raspberrypi/Raspberry-Pi-OS-64bit#7]
When compiling custom Kernel on RPI4 - 4GB running 64bit OS, I get the following error:

```
pi@raspberrypi:~/linux $ KERNEL=kernel8
pi@raspberrypi:~/linux $ make bcm2711_defconfig
#
# configuration written to .config
#
pi@raspberrypi:~/linux $ make -j4 zImage modules dtbs
scripts/kconfig/conf  --syncconfig Kconfig
make: *** No rule to make target 'zImage'.  Stop.
pi@raspberrypi:~/linux $

```

**Comment by rbollampally** [comment]
Ignore. It should be "Image" not "zImage" for 64bit

**Comment by lurch** [comment]
ping @JamesH65 @pelwell ?

**Comment by JamesH65** [comment]
I guess we are going to need some adjustments to the kernel building pages to cope with 64 bit compiling. Is that likely to be a moving target at the moment, or could it be done now?

**Comment by pelwell** [comment]
I can't see the build instructions changing much. Only the DTB installation could do with a bit of work.
