### ISSUE TITLE
Is there any plan to release the release version?

### ISSUE THREAD

**Issue by mushroomlb** [raspberrypi/Raspberry-Pi-OS-64bit#75]
Is there any plan to release the release version?

**Comment by pelwell** [comment]
Yes - when it's ready.

**Comment by hydra3333** [comment]
ha ha, nice answer 🥇 
i used to be in software, and used to get tons of stick for embracing that approach (and the consequences of releasing software with issues were not zero).  
at one point a brand new manager who'd never been in the business before told us we did too much testing ... as funny as.

**Comment by mushroomlb** [comment]
boeing (✪ω✪)
