### ISSUE TITLE
Unable to change password via command line

### ISSUE THREAD

**Issue by alkuentrus** [raspberrypi/Raspberry-Pi-OS-64bit#79]
I changed pass for user pi using comand line several times, and it always assumed the default passwd. The only way to change it was using raspberrypi configuration utility.
I am running Raspi OS 64 from a SSD, on Pi4 2GB RAM

**Comment by pelwell** [comment]
What command did you run? The configuration utility just uses `sudo passwd pi` behind the scenes (although it does cope with a different user name if that has been changed).

**Comment by alkuentrus** [comment]
Just `sudo passwd` . Always worked like that. 
And now it works again. Just did change it again. Will close this issue.
