### ISSUE TITLE
GCC 10.1 Error

### ISSUE THREAD

**Issue by MichaelB7** [raspberrypi/Raspberry-Pi-OS-64bit#84]
usr/include/features.h:424:12: fatal error: sys/cdefs.h: No such file or directory
  424 | #  include <sys/cdefs.h>

**Comment by lurch** [comment]
Debian only [packages](https://packages.debian.org/buster/gcc) GCC 8.3.0 ? 

Looks like you might be encountering a [common error](https://www.google.com/search?q=sys%2Fcdefs.h) rather than something specific to 64-bit Raspberry Pi OS? :man_shrugging:

**Comment by MichaelB7** [comment]
I was using an out of package version gcc 10.1 since that is the only version that officially supports C++17, but in this case, was able to compile with the C++17 flag just fine.
